#!/bin/bash

if [[ $EUID -ne 0 || "$SUDO_USER" != "check" ]]; then
    echo "Error: This script can only be run by 'check' with sudo rights."
    exit 1
fi

domain="$1"
url="/var/www/html/${domain}"

if [ -z "domain" ];
then
        echo "Must provide a domain"
        exit 1
else
        if find /etc/bind/zones/ -name "$domain" ;
	then
                mkdir -p "$url"
                echo "welcome ${domain}" >> "$url/index.html"
                echo "<VirtualHost *:80>
        		ServerName $domain
        		DocumentRoot $url
        		CustomLog /var/log/apache2/$domain.log combined
		</VirtualHost>" >> /etc/apache2/sites-available/${domain}.conf
                touch "/var/log/apache2/${1}.log"
        else
                echo "Must provide a valid domain"
                exit 1
        fi
fi
a2ensite "${1}.conf"
sudo systemctl restart apache2
